/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ArtistSearch: typeof import('./src/components/search/ArtistSearch.vue')['default']
    ArtistSearchItem: typeof import('./src/components/search/ArtistSearchItem.vue')['default']
    Combobox: typeof import('@headlessui/vue')['Combobox']
    ComboboxInput: typeof import('@headlessui/vue')['ComboboxInput']
    ComboboxOptions: typeof import('@headlessui/vue')['ComboboxOptions']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
