name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@0609f0983b7a228f052f81ef4c3d6510cae254ad
        with:
          version: 8.4.0
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm build
      - run: pnpm test
