name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test_backend:
    runs-on: ubuntu-latest
    env:
      GENIUS_ACCESS_TOKEN: ${{ secrets.GENIUS_ACCESS_TOKEN }}
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@0609f0983b7a228f052f81ef4c3d6510cae254ad
        with:
          version: 8.5.0
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "pnpm"
          cache-dependency-path: 'backend/pnpm-lock.yaml'
      - run: pnpm install --frozen-lockfile
      - run: pnpm test
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'backend/coverage/lcov-report'

  deploy_coverage:
    needs: test_backend
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2

  test_frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@0609f0983b7a228f052f81ef4c3d6510cae254ad
        with:
          version: 8.5.0
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "pnpm"
          cache-dependency-path: 'frontend/pnpm-lock.yaml'
      - run: pnpx playwright install-deps
      - run: pnpx playwright install
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - run: pnpm test:unit -- --coverage.enabled --coverage.all --coverage.reporter=lcov --coverage.reporter=text-summary 
      - run: pnpm test:e2e
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3

  deploy_serverless:
    runs-on: ubuntu-latest
    needs: test_backend
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@0609f0983b7a228f052f81ef4c3d6510cae254ad
        with:
          version: 8.5.0
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "pnpm"
          cache-dependency-path: '**/pnpm-lock.yaml'
      - run: pnpm install --frozen-lockfile
      - run: pnpm install --frozen-lockfile
        working-directory: ./frontend
      - run: pnpm install --frozen-lockfile
        working-directory: ./backend
      - name: serverless deploy
        uses: serverless/github-action@v3.2
        with:
          entrypoint: /bin/sh
          args: -c "sls deploy && sls frontend:client build && sls frontend:client deploy"
        env:
          GENIUS_ACCESS_TOKEN: ${{ secrets.GENIUS_ACCESS_TOKEN }}
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
      
    
